baseURL = "docs.kayzor.com/"
languageCode = "en-us"
title = "Kayzor project documentation"
theme = "dot-hugo-documentation-theme"

[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

# English Language
[Languages.en]
languageName = "En"
weight = 10
languageCode = "en-us"
title = "Kayzor Documentation"
dateFormat = "2 January 2006"
home = "Home"
logo = "Kayzor Logo" # TODO
copyright = "Kayzor copyright" # TODO

# navigation
# [[Languages.en.menu.main]]
# weight = 20
# name = "FAQ"
# url = "/faq"

# [[Languages.en.menu.main]]
# weight = 30
# name = "all"
# URL = "/all"

[[Languages.en.menu.contact]]
weight = 70
name = "contact"
url = "/contact"

[[Languages.en.menu.main]]
weight = 40
name = "admin"
url = "/admin"
hasChildren = true

[[Languages.en.menu.main]]
weight = 50
name = "web"
url = "/web"
hasChildren = true

[[Languages.en.menu.main]]
weight = 60
name = "reports"
url = "/reports"
hasChildren = true


# ADMIN children
[[Languages.en.menu.main]]
parent = "admin"
name = "Dashboard"
URL = "/admin/dashboard"
weight = 10

[[Languages.en.menu.main]]
parent = "admin"
name = "Users"
URL = "/admin/users"
weight = 20

[[Languages.en.menu.main]]
parent = "admin"
name = "Roles"
URL = "/admin/roles"
weight = 30

[[Languages.en.menu.main]]
parent = "admin"
name = "Tickets"
URL = "/admin/tickets"
weight = 40

[[Languages.en.menu.main]]
parent = "admin"
name = "Events"
URL = "/admin/events"
weight = 50

[[Languages.en.menu.main]]
parent = "admin"
name = "Finance"
URL = "/admin/finance"
weight = 60

[[Languages.en.menu.main]]
parent = "admin"
name = "Settings"
URL = "/admin/settings"
weight = 70


# WEB children
[[Languages.en.menu.main]]
parent = "web"
name = "Main Page"
URL = "/web/main-page"
weight = 10

[[Languages.en.menu.main]]
parent = "web"
name = "User Panel"
URL = "/web/user-panel"
weight = 20


# REPORTS children
# [[Languages.en.menu.main]]
# parent = "reports"
# name = ""
# URL = ""
# weight = 20


# banner
[Languages.en.params.banner]
title = "Kayzor Documentation Title"
description = "Find advice and answers from our support team fast or get in touch"
image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# Topics
[Languages.en.params.topics]
title = "Find your answer by subject"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
btnText = "contact us"
btnURL = "/contact"

# About
[Languages.en.params.about]
info = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# Contact
[Languages.en.params.contact]
address = "Gostauto 8, Vilnius, 01108, Lithuania"
phone = "+37067031965"
email = "info@kayzor.com"

# API sections
[[Languages.en.menu.api]]
weight = 10
name = "admin"
url = "/admin"

[[Languages.en.menu.api]]
weight = 20
name = "web"
url = "/web"
