baseURL = "docs.kayzor.com/"
languageCode = "en-us"
title = "Kayzor project documentation"
theme = "dot-hugo-documentation-theme"

[params]
primaryColor = "#3072d3"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"
blueOne = "#2695fc"
blueTwo = "#4371c7"
blueThree = "#0e3f91"

[Languages]

# English Language
[Languages.en]
languageName = "En"
weight = 10
languageCode = "en-us"
title = "Kayzor Documentation"
dateFormat = "2 January 2006"
home = "Home"
logoHeader = "svg/logo-header.svg"
logoFooter = "svg/logo-footer.svg"
copyright = "© 2019 Kayzor℠, All Rights Reserved."

[[Languages.en.menu.main]]
weight = 40
name = "admin"
url = "/admin"
hasChildren = true

[[Languages.en.menu.main]]
weight = 50
name = "web"
url = "/web"
hasChildren = true

[[Languages.en.menu.main]]
weight = 60
name = "reports"
url = "/reports"
hasChildren = true


# ADMIN children
[[Languages.en.menu.main]]
parent = "admin"
name = "dashboard"
URL = "/admin/dashboard"
weight = 10

[[Languages.en.menu.main]]
parent = "admin"
name = "users"
URL = "/admin/users"
weight = 20

[[Languages.en.menu.main]]
parent = "admin"
name = "roles"
URL = "/admin/roles"
weight = 30

[[Languages.en.menu.main]]
parent = "admin"
name = "tickets"
URL = "/admin/tickets"
weight = 40

[[Languages.en.menu.main]]
parent = "admin"
name = "events"
URL = "/admin/events"
weight = 50

[[Languages.en.menu.main]]
parent = "admin"
name = "finance"
URL = "/admin/finance"
weight = 60

[[Languages.en.menu.main]]
parent = "admin"
name = "settings"
URL = "/admin/settings"
weight = 70
hasChildren = true

# SETTINGS children
[[Languages.en.menu.main]]
parent = "settings"
name = "currencies"
weight = 40


# WEB children
[[Languages.en.menu.main]]
parent = "web"
name = "main-page"
URL = "/web/main-page"
weight = 10

[[Languages.en.menu.main]]
parent = "web"
name = "user-panel"
URL = "/web/user-panel"
weight = 20


# REPORTS children
# [[Languages.en.menu.main]]
# parent = "reports"
# name = ""
# URL = ""
# weight = 20


# banner
[Languages.en.params.banner]
title = "Kayzor Documentation"
description = "Find advice and answers from our support team fast or get in touch"
image = "images/banner.png"
placeholder = "Have a question? Just ask here or enter terms"

# Topics
[Languages.en.params.topics]
title = "Find documentation by product"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
description = "Worry not, we can give you some extra help."
name = "contact"
url = "/contact"
btnText = "contact us"

[Languages.en.params.contact]
title = "CONTACT US"
content = "Use our message form to send us any questions, comments or suggestions."
formspree_account = "info@kayzor.com"
categories = [
    "General inquiry",
    "Web app", "Admin app",
    "Reports app",
    "Sales",
    "Other"
]


# Info
[Languages.en.params.info]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
address = "Gostauto 8, Vilnius, 01108, Lithuania"
email = "info@kayzor.com"
phone = "+37067031965"

# API sections
[[Languages.en.menu.api]]
weight = 10
name = "admin"
url = "/admin"

[[Languages.en.menu.api]]
weight = 20
name = "web"
url = "/web"
